export class MapResources {
  static MARKER_IMAGE_URI =
    // eslint-disable-next-line max-len
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAkCAMAAADfNcjQAAAAZlBMVEVHcEwOZtsRb+sQa+QACRUAAAAACRYAAAAAAAAAAAAPZ90ENnYLWsEOZtkLXMYACh0PZtoIRJQJTq4MWsIMXskMWL4NYc4Xev////8UdvjA2/9MmP8qhf/x9/9urP+Euf+nzf/w9//zwvd5AAAAF3RSTlMA9f7yEwkNAgQG6zVo3Xgdy0QvYJWGs5XAyv4AAAE3SURBVDjLtVPbdoMgEAz3BS+oxBjNtf//kzUsClLtUzsPHnHGnWEXTqc/hVIKYH6oAxp05+radRr2JDNdVoZRykhV7kgU8IaNg8fIGp4rlJYk0F5CpFbZ/2TYgEhIFSCacSsYGwGpQcmGDKzUMQbICgvc3tP0vmOJSkIs0Bnkrx43vzDdmlMJhw4TCib0cCIKauq/PVDw5Re0FksIkEFwDQiCNQTIcsfCuFWgRIshnyh4oqBdLZTgYZuvOcXjhds0PIbU/ExDf+738ELPXCeNKkjeSVLERn08LvksLlzEVs/DLsyPAunAQcQUmKDn6TQ/JWw68LGy+YkR3CYmxqYJFpO4E9JuDfDQSb4EZY5vD9wSI9RgLZd652Z4RUWpOeBRYfveHvGYY8Yh76+fEPqYx/v9G/0/+AZXwSdMTA54/wAAAABJRU5ErkJggg==';

  static MARKER_ICON = {
    uri: MapResources.MARKER_IMAGE_URI,
    size: { width: 32, height: 36 },
  };
}
